### ISSUE TITLE
little issue..

### ISSUE THREAD

**Issue by huzefa52** [MaclawStudio/aosp#66] opened 2013-02-17 16:20 UTC
The backlight of the softkeys stayed on after turning off the screen.... it remains on  after changing the brightness ...need reboot to fix it....... ...plz fix it
and wifi take long to connect ...
very nice rom very smooth ....no bugs..
waiting for rc4 ics aosp..
thanks maclaw & marcin..

**Comment by exeuntfor** [comment] 2013-02-17 17:08
yes this problem appering on my gio

after change brighness

**Comment by fantostisch** [comment] 2013-02-19 17:42
Same problem here

**Comment by jbaanus** [comment] 2013-02-21 12:44
Duplicate of #67

**Closed as completed** 2013-02-25 16:56 UTC
