### ISSUE TITLE
(CM9 Final1 ACE) YouTube HQ doesn't work

### ISSUE THREAD

**Issue by dundee-81** [MaclawStudio/aosp#149] opened 2013-03-22 20:12 UTC
On Galaxy Ace YouTube HQ doesn't work for me.
After enabling HQ option video loses its smoothness.
It would be glad if you could fix this.

**Comment by MardonHH** [comment] 2013-03-22 20:53
Duplicate of issue #133

**Closed as completed by MardonHH** 2013-03-22 20:53 UTC
