### ISSUE TITLE
(ICS Final 1) Some HQ videos have funny colors

### ISSUE THREAD

**Issue by benjaminzer** [MaclawStudio/aosp#143] opened 2013-03-21 05:04 UTC
This issue is about the S5830 version of AOSP ICS Final 1

Actually, this is a common problem to all ICS/JB ROMs for the particular model. Although it can run HQ smoothly and well, some HQ videos (on YouTube for example) gives funny colors. It is like as if the colors are not aligned properly to its object. The colors float elsewhere in the screen, leaving the object black and white.

Will be great if you guys will strive on to fix this problem. Thank you. Your work is fully appreciated :)

**Comment by MardonHH** [comment] 2013-03-21 13:47
Duplicate of Issue #133

**Closed as completed by MardonHH** 2013-03-21 13:47 UTC
