### ISSUE TITLE
[CM9 final1] Backlight doesn't turn off

### ISSUE THREAD

**Issue by baej-ultra** [MaclawStudio/aosp#182] opened 2013-04-03 10:49 UTC
Sometimes softkeys' backlight doesn't turn off and stays on with no particular reason. ROM CM9 for Galaxy Gio.
Pozdrawiam.

**Comment by baej-ultra** [comment] 2013-04-03 11:25
Noticed that it happens after i change screen brightness by sliding on status bar.

**Comment by mabl** [comment] 2013-04-09 15:15
I also noticed that. 

The problem also appears when changing the brightness in the settings. After this, changing /sys/class/leds/button-backlight/brightness won't have any effect on the soft key brightness.

**Comment by mabl** [comment] 2013-04-09 15:18
Changing the screen brightness via /sys/class/leds/lcd-backlight/brightness won't effect the softkeys though. I guess Android does not only try to change the lcd backlight but also the button backlight, which will trigger this bug.

**Comment by guilherme-blatt** [comment] 2013-04-13 22:41
this is fixed in final 2

**Comment by mabl** [comment] 2013-04-14 12:49
Ineed. I've updated and the problem is fixed. Thank you.

**Comment by maclaw** [comment] 2013-04-19 13:38
So why didn't you closed this issue?

**Closed as completed** 2013-04-19 13:40 UTC
